name: Pytest

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        echo "$(python -c 'import os,sys; print(os.path.realpath(sys.executable))')/$(echo $(python -c 'import sys; print(sys.executable)') | rev | cut -d'/' -f1 | rev)" > "$(python -c 'import site; print(site.USER_BASE)')/bin/python"
        echo "PATH=$(python -c 'import site; print(site.USER_BASE)')/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies with Poetry
      run: |
        poetry config virtualenvs.create false
        poetry install

    - name: Run pytest
      env:
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
      run: |
        poetry run pytest -s vectordb_orm
